using PKHeX.Core;
using PKHeX.Presentation.Localization;

namespace PKHeX.Presentation.ViewModels;

/// <summary>Facility ordering and color palettes follow kwsch/PKHeX SAV_FestivalPlaza (GPL-3.0).</summary>
internal static class PlazaCatalog
{
    private static string T(string key) => LocalizedStrings.Instance[key];
    private static ComboItem Unknown(int value) => new(LocalizedStrings.Instance.Format("PlazaSession_Unknown", value), value);
    private static IReadOnlyList<ComboItem> Preserve(List<ComboItem> items, int value)
    { if (!items.Any(i => i.Value == value)) items.Add(Unknown(value)); return items; }
    public static IReadOnlyList<ComboItem> TypeChoices(bool ultra, int current)
    {
        (int Family, int Shop, int Level)[] definitions = [
            (0,0,1),
            (0,0,2),
            (0,0,3),
            (0,0,4),
            (0,0,5),
            (0,1,1),
            (0,1,2),
            (0,1,3),
            (0,1,4),
            (0,1,5),
            (0,2,1),
            (0,2,2),
            (0,2,3),
            (0,2,4),
            (0,2,5),
            (1,0,1),
            (1,0,2),
            (1,0,3),
            (1,0,4),
            (1,0,5),
            (1,1,1),
            (1,1,2),
            (1,1,3),
            (1,1,4),
            (1,1,5),
            (1,2,1),
            (1,2,2),
            (1,2,3),
            (1,2,4),
            (1,2,5),
            (2,0,1),
            (2,0,2),
            (2,0,3),
            (2,1,1),
            (2,1,2),
            (2,1,3),
            (2,1,4),
            (2,1,5),
            (2,2,1),
            (2,2,2),
            (2,2,3),
            (2,3,1),
            (2,3,2),
            (2,3,3),
            (2,4,1),
            (2,4,2),
            (2,4,3),
            (3,0,1),
            (3,0,2),
            (3,0,3),
            (3,0,4),
            (3,0,5),
            (3,1,1),
            (3,1,3),
            (3,1,5),
            (3,2,1),
            (3,2,2),
            (3,2,3),
            (3,2,4),
            (3,2,5),
            (3,3,1),
            (3,3,2),
            (3,3,3),
            (3,3,4),
            (3,3,5),
            (4,0,1),
            (4,0,2),
            (4,0,3),
            (4,0,4),
            (4,0,5),
            (4,1,1),
            (4,1,2),
            (4,1,3),
            (4,1,4),
            (4,1,5),
            (4,2,1),
            (4,2,2),
            (4,2,3),
            (4,2,4),
            (4,2,5),
            (5,0,1),
            (5,0,3),
            (5,0,5),
            (5,1,1),
            (5,1,3),
            (5,1,5),
            (5,2,1),
            (5,2,3),
            (5,2,5),
            (5,3,1),
            (5,3,3),
            (5,3,5),
            (5,4,1),
            (5,4,3),
            (5,4,5),
            (5,5,1),
            (5,5,3),
            (5,5,5),
            (5,6,1),
            (5,6,3),
            (5,6,5),
            (6,0,1),
            (6,0,3),
            (6,0,5),
            (6,1,1),
            (6,1,3),
            (6,1,5),
            (6,2,1),
            (6,2,3),
            (6,2,5),
            (6,3,1),
            (6,3,3),
            (6,3,5),
            (6,4,1),
            (6,4,3),
            (6,4,5),
            (6,5,1),
            (6,5,3),
            (6,5,5),
            (6,6,1),
            (6,6,3),
            (6,6,5),
            (6,7,1),
            (6,7,3),
            (6,7,5),
            (7,0,1),
            (7,0,2),
            (7,0,3),
        ];
        var count = ultra ? 128 : 125;
        return Preserve(definitions.Take(count).Select((d, i) => new ComboItem(
            $"{T($"PlazaSession_Family{d.Family}")} {T($"PlazaSession_Sub{d.Family}_{d.Shop}")} ★{d.Level}", i)).ToList(), current);
    }
    public static IReadOnlyList<ComboItem> ColorChoices(int type, int current)
    {
        int[][] palettes = [[0,1,2,3],[4,0,5,3],[1,0,5,3],[6,7,0,3],[4,5,8,3],[0,1,2,3],[0,7,8,4,5,1,9,10],[11,1,5,3]];
        var family = type switch { < 0 => -1, < 15 => 0, < 30 => 1, < 47 => 2, < 65 => 3, < 80 => 4, < 101 => 5, < 125 => 6, < 128 => 7, _ => -1 };
        return family < 0 ? [Unknown(current)] : Preserve(palettes[family].Select((color, i) => new ComboItem(T($"PlazaSession_Color{color}"), i)).ToList(), current);
    }
    public static IReadOnlyList<ComboItem> NpcChoices(int current) => Preserve(Enumerable.Range(0, 12).Select(i => new ComboItem(T($"PlazaSession_Npc{i}"), i)).ToList(), current);
    public static IReadOnlyList<ComboItem> GenderChoices(int current) => Preserve(Enumerable.Range(0, 2).Select(i => new ComboItem(T($"PlazaSession_Gender{i}"), i)).ToList(), current);
    public static IReadOnlyList<ComboItem> RewardChoices(int current) => Preserve(Enumerable.Range(0, 3).Select(i => new ComboItem(T($"PlazaSession_RewardState{i}"), i)).ToList(), current);
}
